### ISSUE TITLE
Adding additional edges does not respect individual trust limits between nodes

### ISSUE THREAD

**Issue by samuelandert** [CirclesUBI/circles-transfer#1]
When I make transactions over circles.garden to directly trusted peers, in the notifications the transaction shows instantly up, but the safe balance is not updating accordingly for many hours.

**Comment by ana0** [comment]
I think this is a duplicate of https://github.com/CirclesUBI/circles-subgraph/issues/20

**Comment by adzialocha** [comment]
The transfer steps between Samuel and Phibar were not valid as the original algorithm suggested transferring 50 Circles over an edge which only had a capacity of 38. The contracts rejected that transfer correctly.

I've fixed this issue here: https://github.com/CirclesUBI/circles-transfer/commit/17bd011e5d4c2487dbe61007917ce4539324b648

@ana0 I'm not sure if this is a duplicate issue, as the one you mention is about not recorded valid transactions in the subgraph which got mined. The issue here caused transactions to not get mined as they were invalid.
